export const SET_USER = 'SET_USER'

export const SET_NOWCOMPANY_ID = 'SET_NOWCOMPANY_ID'

export const SET_COM_PERSON_LIST = 'SET_COM_PERSON_LIST'

export const SET_COM_DEPART_LIST = 'SET_COM_DEPART_LIST'

